# Generated by Django 2.1 on 2023-02-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('datetime_signin', models.DateTimeField(auto_now_add=True)),
                ('dentist_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('dentist_name', models.CharField(max_length=100)),
                ('dentist_fathers_ln', models.CharField(max_length=100)),
                ('dentist_monthers_ln', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('year_birth', models.PositiveSmallIntegerField()),
                ('month_birth', models.PositiveSmallIntegerField()),
                ('day_birth', models.PositiveSmallIntegerField()),
                ('phone_country_lada', models.CharField(max_length=4)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('university_name', models.CharField(max_length=50)),
                ('postgrade_name', models.CharField(max_length=50)),
                ('postgrade_u_name', models.CharField(max_length=50)),
                ('curr_company_name', models.CharField(max_length=50)),
                ('start_work_year', models.IntegerField()),
                ('start_work_month', models.IntegerField()),
                ('company_worked_2', models.CharField(max_length=50)),
                ('start_work_year_2', models.IntegerField(default=None, null=True)),
                ('start_work_month_2', models.IntegerField(default=None, null=True)),
                ('company_worked_3', models.CharField(max_length=50)),
                ('start_work_year_3', models.IntegerField(default=None, null=True)),
                ('start_work_month_3', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('datetime_signin', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_fathers_ln', models.CharField(max_length=100)),
                ('patient_monthers_ln', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('year_birth', models.PositiveSmallIntegerField()),
                ('month_birth', models.PositiveSmallIntegerField()),
                ('day_birth', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('profession', models.CharField(default=None, max_length=50, null=True)),
                ('education_level', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentTape',
            fields=[
                ('datetime_apppointment', models.DateTimeField(auto_now_add=True)),
                ('treatment_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('treatment_name', models.CharField(max_length=100)),
                ('treatment_status', models.CharField(max_length=100)),
                ('treatment_priority', models.CharField(max_length=6)),
                ('treatment_time_hours', models.DecimalField(decimal_places=2, max_digits=2)),
                ('amt_revenue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('material_used_01', models.CharField(default=None, max_length=20, null=True)),
                ('material_used_02', models.CharField(default=None, max_length=20, null=True)),
                ('material_used_03', models.CharField(default=None, max_length=20, null=True)),
                ('material_used_04', models.CharField(default=None, max_length=20, null=True)),
                ('material_used_05', models.CharField(default=None, max_length=20, null=True)),
                ('comments', models.TextField(default=None, max_length=200, null=True)),
                ('nu_follow_appointments', models.PositiveSmallIntegerField()),
                ('priority_next_appointment', models.CharField(max_length=100)),
                ('datetime_next_appointment', models.DateTimeField()),
                ('dentist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dentist')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
            ],
        ),
    ]
